#!/usr/bin/env bash
# claude-passthru atomic rule remove wrapper.
#
# Usage:
#   remove-rule.sh <scope> <list> <index>
#   scope = user|project
#   list  = allow|deny|ask
#   index = 1-based position within the authored file's list array
#
# Behaviour:
#   1. Resolve target authored passthru.json path (user or project scope).
#   2. Only operates on authored files. Imported files are regenerated by
#      scripts/bootstrap.sh; removing a rule from an imported file manually
#      would be clobbered on next bootstrap, so we refuse and point the user
#      at bootstrap.
#   3. Take a backup of the current file, splice out the indexed rule via jq,
#      run scripts/verify.sh --quiet. On failure: restore backup, exit 2.
#      On success: delete backup, exit 0.
#   4. Uses the same mkdir-based lock as write-rule.sh so add+remove are
#      serialized against concurrent writers.
#
# Exit codes:
#   0 success
#   1 invalid args / rule not found / scope rejected / missing file
#   2 verifier failure (rolled back)
#
# On success: prints "removed <scope>/<list>/<index>: <tool-summary>" to
# stdout so Claude can relay the confirmation back.

set -euo pipefail

# ---------------------------------------------------------------------------
# Locate scripts + common.sh
# ---------------------------------------------------------------------------
if [ -n "${CLAUDE_PLUGIN_ROOT:-}" ] && [ -f "${CLAUDE_PLUGIN_ROOT}/hooks/common.sh" ]; then
  _PASSTHRU_PLUGIN_ROOT="$CLAUDE_PLUGIN_ROOT"
else
  _PASSTHRU_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  _PASSTHRU_PLUGIN_ROOT="$(cd "${_PASSTHRU_SCRIPT_DIR}/.." && pwd)"
fi

# shellcheck disable=SC1091
source "${_PASSTHRU_PLUGIN_ROOT}/hooks/common.sh"

VERIFY_SH="${_PASSTHRU_PLUGIN_ROOT}/scripts/verify.sh"
if [ ! -x "$VERIFY_SH" ] && [ ! -f "$VERIFY_SH" ]; then
  printf 'remove-rule.sh: cannot locate scripts/verify.sh (looked in %s)\n' "$VERIFY_SH" >&2
  exit 1
fi

# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------

if [ $# -ne 3 ]; then
  cat <<USAGE >&2
usage: remove-rule.sh <scope> <list> <index>
  scope = user|project
  list  = allow|deny|ask
  index = 1-based position within the authored file's list array
USAGE
  exit 1
fi

SCOPE="$1"
LIST="$2"
INDEX_ARG="$3"

case "$SCOPE" in
  user|project) ;;
  *) printf 'remove-rule.sh: invalid scope: %s (want user|project)\n' "$SCOPE" >&2; exit 1 ;;
esac

case "$LIST" in
  allow|deny|ask) ;;
  *) printf 'remove-rule.sh: invalid list: %s (want allow|deny|ask)\n' "$LIST" >&2; exit 1 ;;
esac

if ! [[ "$INDEX_ARG" =~ ^[0-9]+$ ]] || [ "$INDEX_ARG" -lt 1 ]; then
  printf 'remove-rule.sh: index must be a positive integer (got: %s)\n' "$INDEX_ARG" >&2
  exit 1
fi
INDEX="$INDEX_ARG"

# ---------------------------------------------------------------------------
# Resolve target path (authored only)
# ---------------------------------------------------------------------------

case "$SCOPE" in
  user)    TARGET="$(passthru_user_authored_path)" ;;
  project) TARGET="$(passthru_project_authored_path)" ;;
esac

if [ ! -f "$TARGET" ]; then
  printf 'remove-rule.sh: authored rule file not found: %s\n' "$TARGET" >&2
  exit 1
fi

if ! jq -e '.' "$TARGET" >/dev/null 2>&1; then
  printf 'remove-rule.sh: existing authored file does not parse as JSON: %s\n' "$TARGET" >&2
  exit 1
fi

# ---------------------------------------------------------------------------
# Detect whether the user is trying to remove an imported rule
# ---------------------------------------------------------------------------
# remove-rule.sh always points at the authored file. If the caller meant the
# imported file, the index within the authored file will either be out of
# range or point at a different rule. We cannot tell which from the command
# alone, so the message below guides them to bootstrap.
#
# The "cannot remove imported" path is only reachable when the authored file
# has zero rules in the chosen list but the imported file has some (which is
# the usual post-bootstrap shape). We detect that and emit the spec's exact
# error message.

AUTHORED_LIST_LEN="$(jq -r --arg l "$LIST" '.[$l] // [] | length' "$TARGET")"

if [ "$AUTHORED_LIST_LEN" -eq 0 ]; then
  # Check if the imported file has rules in this list. If so, the user
  # likely meant to remove an imported rule.
  case "$SCOPE" in
    user)    IMPORTED="$(passthru_user_imported_path)" ;;
    project) IMPORTED="$(passthru_project_imported_path)" ;;
  esac
  IMPORTED_LEN=0
  if [ -f "$IMPORTED" ] && jq -e '.' "$IMPORTED" >/dev/null 2>&1; then
    IMPORTED_LEN="$(jq -r --arg l "$LIST" '.[$l] // [] | length' "$IMPORTED")"
  fi
  if [ "$IMPORTED_LEN" -ge "$INDEX" ]; then
    printf 'remove-rule: cannot remove imported rule at %s/%s/%s. Re-run scripts/bootstrap.sh --write to regenerate imports.\n' \
      "$SCOPE" "$LIST" "$INDEX" >&2
    exit 1
  fi
  printf 'remove-rule.sh: no rules in %s/%s (authored): nothing at index %s\n' \
    "$SCOPE" "$LIST" "$INDEX" >&2
  exit 1
fi

if [ "$INDEX" -gt "$AUTHORED_LIST_LEN" ]; then
  printf 'remove-rule.sh: index %s out of range for %s/%s (has %s authored rules)\n' \
    "$INDEX" "$SCOPE" "$LIST" "$AUTHORED_LIST_LEN" >&2
  exit 1
fi

# ---------------------------------------------------------------------------
# Lock acquisition (mkdir-only, same pattern as write-rule.sh)
# ---------------------------------------------------------------------------

USER_CLAUDE_DIR="${PASSTHRU_USER_HOME:-$HOME}/.claude"
mkdir -p "$USER_CLAUDE_DIR"
LOCK_DIR="$USER_CLAUDE_DIR/passthru.write.lock.d"
LOCK_TIMEOUT="${PASSTHRU_WRITE_LOCK_TIMEOUT:-5}"

LOCK_HELD=0

acquire_lock() {
  local deadline
  deadline=$(( $(date +%s) + LOCK_TIMEOUT ))
  while :; do
    if mkdir "$LOCK_DIR" 2>/dev/null; then
      printf '%s\n' "$$" > "$LOCK_DIR/pid" 2>/dev/null || true
      LOCK_HELD=1
      return 0
    fi
    # Stale lock detection: check if holder PID is still alive.
    if [ -f "$LOCK_DIR/pid" ]; then
      local holder_pid
      holder_pid="$(cat "$LOCK_DIR/pid" 2>/dev/null || true)"
      if [ -n "$holder_pid" ] && ! kill -0 "$holder_pid" 2>/dev/null; then
        rm -f "$LOCK_DIR/pid" 2>/dev/null || true
        rmdir "$LOCK_DIR" 2>/dev/null || true
        continue
      fi
    fi
    if [ "$(date +%s)" -ge "$deadline" ]; then
      return 1
    fi
    sleep 0.1
  done
}

release_lock() {
  if [ "$LOCK_HELD" -eq 1 ]; then
    rm -f "$LOCK_DIR/pid" 2>/dev/null || true
    rmdir "$LOCK_DIR" 2>/dev/null || true
    LOCK_HELD=0
  fi
}

if ! acquire_lock; then
  printf 'remove-rule.sh: failed to acquire lock %s within %ss\n' "$LOCK_DIR" "$LOCK_TIMEOUT" >&2
  exit 1
fi

# Trap cleanup mirrors write-rule.sh's STATE machine so a signal between
# mv-target and verifier-rollback leaves the file intact.
BACKUP=""
STATE="NONE"

cleanup() {
  local rc=$?
  if [ "$STATE" = "WRITING" ] && [ -n "$BACKUP" ] && [ -f "$BACKUP" ]; then
    mv "$BACKUP" "$TARGET" 2>/dev/null || true
    BACKUP=""
  fi
  release_lock
  if [ -n "$BACKUP" ] && [ -f "$BACKUP" ]; then
    rm -f "$BACKUP" 2>/dev/null || true
  fi
  exit $rc
}
trap cleanup EXIT
trap 'exit 1' INT TERM

# ---------------------------------------------------------------------------
# Take backup, splice out the indexed rule
# ---------------------------------------------------------------------------

BACKUP="$(mktemp "${TARGET}.backup.XXXXXX")"
cp -p "$TARGET" "$BACKUP"
STATE="BACKED_UP"

# Capture the rule being removed (for the success message) before we splice.
JQ_IDX=$((INDEX - 1))
REMOVED_RULE="$(jq -c --argjson i "$JQ_IDX" --arg l "$LIST" '.[$l][$i]' "$TARGET")"
if [ -z "$REMOVED_RULE" ] || [ "$REMOVED_RULE" = "null" ]; then
  printf 'remove-rule.sh: rule at %s/%s/%s not found (internal bounds check failed)\n' \
    "$SCOPE" "$LIST" "$INDEX" >&2
  exit 1
fi

NEW_CONTENT="$(
  jq --argjson i "$JQ_IDX" --arg list "$LIST" '
    (.version // 1) as $v
    | .version = $v
    | .allow = (.allow // [])
    | .deny  = (.deny // [])
    # Preserve an existing ask[] on v2 files. Do NOT materialize a fresh
    # ask[] on v1 files - that would silently promote the schema, which
    # write-rule.sh deliberately avoids too. The pre-splice bounds check
    # guarantees that when $list == "ask" the key already exists with at
    # least one element, so the del below is always safe.
    | (if $v >= 2 then .ask = (.ask // []) else . end)
    | .[$list] = (.[$list] | del(.[$i]))
  ' "$TARGET"
)" || {
  printf 'remove-rule.sh: jq failed to splice out the rule\n' >&2
  exit 1
}

TMPOUT="$(mktemp "${TARGET}.tmp.XXXXXX")"
printf '%s\n' "$NEW_CONTENT" > "$TMPOUT"
STATE="WRITING"
mv "$TMPOUT" "$TARGET"

# ---------------------------------------------------------------------------
# Verify
# ---------------------------------------------------------------------------

VERIFY_ERR=""
set +e
VERIFY_ERR="$(bash "$VERIFY_SH" --quiet 2>&1 >/dev/null)"
VERIFY_RC=$?
set -e

if [ "$VERIFY_RC" -ne 0 ]; then
  mv "$BACKUP" "$TARGET"
  BACKUP=""
  STATE="VERIFIED"
  printf 'remove-rule.sh: verifier rejected new state after remove; rolled back\n' >&2
  if [ -n "$VERIFY_ERR" ]; then
    printf '%s\n' "$VERIFY_ERR" >&2
  fi
  exit 2
fi

STATE="VERIFIED"
rm -f "$BACKUP"
BACKUP=""

# ---------------------------------------------------------------------------
# Success message
# ---------------------------------------------------------------------------

# Build a short tool-summary: "tool=X, match.key=pat" or "tool=X" alone.
TOOL_SUMMARY="$(jq -r '
  ( if (.tool // null) != null then "tool=\(.tool)" else "" end ) as $t
  | ( if (.match // null) != null and (.match | length) > 0 then
        ( .match | to_entries | map("\(.key)=\(.value)") | join(", ") )
      else "" end ) as $m
  | [ $t, $m ] | map(select(. != "")) | join(", ")
' <<<"$REMOVED_RULE")"

if [ -z "$TOOL_SUMMARY" ]; then
  TOOL_SUMMARY="(no tool/match)"
fi

printf 'removed %s/%s/%s: %s\n' "$SCOPE" "$LIST" "$INDEX" "$TOOL_SUMMARY"
exit 0
